### ISSUE TITLE
Grails 4 upgrade

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocache-hubs#500]
It includes the fellowing apps Grails4 upgrade, they both exist in grails4 branch

**Upstream app:**
ala-hub 

**dependent libs :**

ala-bootstrap3: 3.4.0-snapshot    https://github.com/AtlasOfLivingAustralia/ala-bootstrap3/tree/grails4
downloads-plugin: 3.0-SNAPSHOT https://github.com/AtlasOfLivingAustralia/downloads-plugin/tree/grails4 
images-client-plugin: 1.4-SNAPSHOT https://github.com/AtlasOfLivingAustralia/images-client-plugin/tree/grails4
ala-charts-plugin: 2.2 https://github.com/AtlasOfLivingAustralia/ala-charts-plugin/tree/grails4

**Todo**:
After finishing the review/release of dependent libs, the related versions used in Ala-hub and biocache-hub should be upgraded to release versions

**Comment by nickdos** [comment]
@brucehyslop code review grails 4 branches of:
- [ ] biocache-hubs
- [ ] ala-hub
- [ ] ala-bootstrap3
- [ ] downloads-plugin

**Comment by brucehyslop** [comment]
There are some more ALA plugins that are dependencies of the `ala-hub` project that may need to be updated
- [ ] [ala-admin-plugin](https://github.com/AtlasOfLivingAustralia/ala-admin-plugin)
- [ ] [ala-auth](https://github.com/AtlasOfLivingAustralia/ala-auth-plugin)
- [ ] [ala-ws-plugin](https://github.com/AtlasOfLivingAustralia/ala-ws-plugin)
- [ ] [http-builder-helper](https://github.com/AtlasOfLivingAustralia/grails-http-builder-helper) (v1.0.2.ALA it looks like there is an ALA fork)

**Comment by brucehyslop** [comment]
The skin / layout for `ala-hub` has been changed from `ala` to `ala-main`. Both these layouts have a similar look and feel however there are minor differences. 

The `ala` layout is defined in the `ala-hub` project and the `ala-main` layout in `ala-bootstrap3` 

The `ala` layout does not work on the grails4 branch.

**Comment by brucehyslop** [comment]
The display of occurrence records that have a `collectionUid` return an error. 

see: [http://dev.ala.org.au:8081/ala-hub/occurrences/search?q=collectionUid:*](http://dev.ala.org.au:8081/ala-hub/occurrences/search?q=collectionUid:*)

```
java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2754)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3809)
	at groovy.lang.MetaClassImpl.setProperties(MetaClassImpl.java:1764)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1741)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1556)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeConstructorOf(InvokerHelper.java:1042)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:385)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:329)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnCollection(DefaultTypeTransformation.java:277)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:230)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:615)
	at au.org.ala.biocache.hubs.WebServicesService.getCollectionContact(WebServicesService.groovy)
	at au.org.ala.biocache.hubs.WebServicesService$getCollectionContact$15.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at au.org.ala.biocache.hubs.OccurrenceController.show(OccurrenceController.groovy:381)
	at au.org.ala.biocache.hubs.OccurrenceController.show(OccurrenceController.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
```

**Comment by brucehyslop** [comment]
The `java.lang.IllegalArgumentException: argument type mismatch` is due to a bug in the grails-cache plugin that caches fails key the called method correctly. 

A patch has been submitted to fix the issue and a deployment a patch release to nexus `org.grails.plugins:cache:5.0.0-ALA:ALA`
